name: contact_list_data
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.4

dependencies:
   contact_list_domain:
    path: ../contact_list_domain
   path: ^1.9.0
   sqflite: ^2.3.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
