name: provider_counter
description: >
  The starter Flutter application, but using Provider to manage state.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.4.0-0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
